/**
 * This file is part of create-ai-chat-context-experimental.
 * Licensed under the GNU Affero General Public License v3.0 or later (AGPL-3.0-or-later).
 * See LICENSE file for details.
 */

/**
 * API Key Scanner
 * Scans .env files for ANTHROPIC_API_KEY and validates it
 * Phase 6: November 2025
 */

import { join } from 'path';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import type { Result } from '../types/result.js';
import { Ok, Err } from '../types/result.js';

export interface ApiKeyScanResult {
  found: boolean;
  file?: string;
  key?: string;
  valid?: boolean;
}

/**
 * API Key Scanner - Find and validate ANTHROPIC_API_KEY
 */
export class ApiKeyScanner {
  private cwd: string;

  constructor(cwd: string = process.cwd()) {
    this.cwd = cwd;
  }

  /**
   * Scan for ANTHROPIC_API_KEY in .env files
   */
  async scan(): Promise<ApiKeyScanResult> {
    // Check common .env file locations
    const envFiles = [
      join(this.cwd, '.env'),
      join(this.cwd, '.env.local'),
      join(this.cwd, '.env.development'),
      join(this.cwd, '.env.production'),
    ];

    for (const file of envFiles) {
      if (existsSync(file)) {
        const key = this.extractKeyFromFile(file);
        if (key) {
          const valid = this.validateKey(key);
          return {
            found: true,
            file,
            key,
            valid,
          };
        }
      }
    }

    // Check environment variable
    const envKey = process.env['ANTHROPIC_API_KEY'];
    if (envKey) {
      const valid = this.validateKey(envKey);
      return {
        found: true,
        file: 'environment variable',
        key: envKey,
        valid,
      };
    }

    return {
      found: false,
    };
  }

  /**
   * Extract ANTHROPIC_API_KEY from .env file
   */
  private extractKeyFromFile(file: string): string | null {
    try {
      const content = readFileSync(file, 'utf-8');
      const lines = content.split('\n');

      for (const line of lines) {
        // Skip comments and empty lines
        if (line.trim().startsWith('#') || line.trim().length === 0) {
          continue;
        }

        // Match ANTHROPIC_API_KEY=sk-ant-...
        const match = line.match(/^\s*ANTHROPIC_API_KEY\s*=\s*(.+)$/);
        if (match && match[1]) {
          let key = match[1].trim();
          // Remove quotes if present
          key = key.replace(/^["']|["']$/g, '');
          return key;
        }
      }

      return null;
    } catch {
      return null;
    }
  }

  /**
   * Validate API key format
   * Anthropic keys start with "sk-ant-"
   */
  private validateKey(key: string): boolean {
    if (!key || key.length === 0) {
      return false;
    }

    // Check if key starts with "sk-ant-"
    if (!key.startsWith('sk-ant-')) {
      return false;
    }

    // Check if key has reasonable length (at least 20 characters)
    if (key.length < 20) {
      return false;
    }

    return true;
  }

  /**
   * Save API key to .env file
   */
  async saveKey(key: string): Promise<Result<void>> {
    try {
      const envFile = join(this.cwd, '.env');
      let content = '';

      // Read existing .env file if it exists
      if (existsSync(envFile)) {
        content = readFileSync(envFile, 'utf-8');

        // Check if ANTHROPIC_API_KEY already exists
        const lines = content.split('\n');
        let keyExists = false;

        for (let i = 0; i < lines.length; i++) {
          const line = lines[i];
          if (line && line.trim().startsWith('ANTHROPIC_API_KEY=')) {
            // Replace existing key
            lines[i] = `ANTHROPIC_API_KEY=${key}`;
            keyExists = true;
          }
        }

        if (keyExists) {
          content = lines.join('\n');
        } else {
          // Append new key
          content += (content.endsWith('\n') ? '' : '\n') + `ANTHROPIC_API_KEY=${key}\n`;
        }
      } else {
        // Create new .env file
        content = `# AETHER Configuration\n# Generated by aether init\n\nANTHROPIC_API_KEY=${key}\n`;
      }

      writeFileSync(envFile, content, 'utf-8');
      return Ok(undefined);
    } catch (error) {
      return Err(error instanceof Error ? error : new Error(String(error)));
    }
  }

  /**
   * Create .env.example file
   */
  async createExample(): Promise<Result<void>> {
    try {
      const exampleFile = join(this.cwd, '.env.example');

      // Don't overwrite existing .env.example
      if (existsSync(exampleFile)) {
        return Ok(undefined);
      }

      const content = `# AETHER Configuration
# Copy this file to .env and fill in your API key

# Claude API Key (required for PrincipleWatcher)
# Get your key from: https://console.anthropic.com/
ANTHROPIC_API_KEY=sk-ant-your-key-here
`;

      writeFileSync(exampleFile, content, 'utf-8');
      return Ok(undefined);
    } catch (error) {
      return Err(error instanceof Error ? error : new Error(String(error)));
    }
  }

  /**
   * Mask API key for display (show first 10 and last 4 characters)
   */
  static maskKey(key: string): string {
    if (key.length <= 14) {
      return '***';
    }
    return `${key.substring(0, 10)}...${key.substring(key.length - 4)}`;
  }
}
